image: nikolaik/python-nodejs:python3.8-nodejs16

stages:
  - deploy

services:
  - docker:18.09-dind

production:
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless serverless-compose
    - npm install --save serverless-python-requirements
  stage: deploy
  script:
    - serverless requirements cleanCache
    - serverless deploy --verbose