image: nikolaik/python-nodejs:python3.9-nodejs16

stages:
  - deploy

services:
  - docker:18.09-dind

production:
  only: 
    - main
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless 
    - npm install serverless-compose
    - npm install --save serverless-python-requirements
  stage: deploy
  script:
    - serverless deploy --verbose