app: cv-ocr
service: cv-ocr
frameworkVersion: '3'

functions:
  cv_question:
    handler: main.questions
    timeout: 60
    events:
      - http:
          path: "/cv_questions"
          method: post
          integration: lambda
  cv_ocr:
    handler: main.parse
    timeout: 30
    events:
      - http:
          path: "/cv_ocr"
          method: post
          integration: lambda
    
package:
  exclude:
    - '!node_modules/**'
    - '!venv/**'
    - '!package-lock.json/**'
    
plugins:
  - serverless-python-requirements  

custom:
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.9
  architecture: x86_64
  region: ap-southeast-1
  apiGateway:
    restApiId: jo4yphs17g
    restApiRootResourceId: 9kl7ci3plk
  environment: 
    OPENAI_API_BASE: ${env:AZURE_OPENAI_ENDPOINT}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    OPENAI_API_TYPE: ${env:OPENAI_API_TYPE}
    OPENAI_API_VERSION: ${env:OPENAI_API_VERSION}
    DEPLOYMENT_NAME: ${env:AZURE_OPENAI_DEPLOYMENT}
    AZURE_VISION_KEY: ${env:AZURE_VISION_KEY}
    AZURE_VISION_ENDPOINT: ${env:AZURE_VISION_ENDPOINT}