app: promotion-generator
service: promotion-generator
frameworkVersion: '3'

package:
  exclude:
    - '!node_modules/**'
    - '!venv/**'
    - '!package-lock.json/**'
    
plugins:
  - serverless-python-requirements  

custom:
  pythonRequirements:
    pythonBin: python3
    
provider:
  name: aws
  runtime: python3.9
  architecture: x86_64
  region: ap-southeast-1
  environment: 
    AZURE_OPENAI_ENDPOINT: ${env:AZURE_OPENAI_ENDPOINT}
    AZURE_OPENAI_KEY: ${env:AZURE_OPENAI_KEY}
    AZURE_OPENAI_DEPLOYMENT: ${env:AZURE_OPENAI_DEPLOYMENT}
    AZURE_VISION_KEY: ${env:AZURE_VISION_KEY}
    AZURE_VISION_ENDPOINT: ${env:AZURE_VISION_ENDPOINT}

functions:
  promotion-generator:
    handler: handler.lambda_handler
    events:
      - http:
          path: "/promotion_generator"
          method: post
          integration: lambda