app: food-image-generator
service: food-image-generator
frameworkVersion: '3'

functions:
  food-image-generate:
    handler: handler.genphoto_handler
    timeout: 30   
    events:
      - http:
          path: "/foodimage_generate"
          method: post
          integration: lambda
  food-image-get:
    handler: handler.getphoto_handler
    timeout: 30
    events:
      - http:
          path: "/foodimage_get"
          method: post
          integration: lambda
    
package:
  exclude:
    - '!node_modules/**'
    - '!venv/**'
    - '!package-lock.json/**'
    
plugins:
  - serverless-python-requirements  

custom:
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.9
  architecture: x86_64
  region: ap-southeast-1
  apiGateway:
    restApiId: jo4yphs17g
    restApiRootResourceId: 9kl7ci3plk
  environment: 
    MIDJOURNEY_ACCOUNT: ${env:MIDJOURNEY_ACCOUNT}
    MIDJOURNEY_PASSWORD: ${env:MIDJOURNEY_PASSWORD}
    GENERATE_N8N_ENDPOINT: ${env:GENERATE_N8N_ENDPOINT}
    GET_N8N_ENDPOINT: ${env:GET_N8N_ENDPOINT}